### ISSUE TITLE
Not running well

### ISSUE THREAD

**Issue by Peter-XL** [cloverstd/GFWList2Surge#1]
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main()
  File "main.py", line 175, in main
    with open(args.input, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'gfwlist.txt'

My Python version is 2.7.3

**Comment by yeuleh** [comment]
Obviously, you haven't prepared a gfwlist text file before running this script.
